firstweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name="register"),
    path('', include('instaclone.urls')),
    path('', include('django.contrib.auth.urls')),
]
if settings.DEBUG:

    urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instaclone/urls.py
from django.urls import path, re_path
from . import views


app_name = 'instaclone'
urlpatterns = [
    path('profile_pic/', views.change_profile_pic, name='profile_pic'),
    path('upload/', views.upload, name='upload'),
    path('home/', views.home, name='home'),
    path('my_profile/', views.my_profile, name='my_profile'),
    re_path(r'^profile/(?P<username>\w+)/$', views.profileview, name="profile"),
    re_path(r'^followers/(?P<username>\w+)/$', views.followers, name='followers'),
    re_path(r'^following/(?P<username>\w+)/$', views.following, name='following'),
    re_path(r'^follow/(?P<username>\w+)/$', views.follow, name='follow'),

]

instaclone/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING,null=True)
    username =  models.CharField(max_length=100, default='',null=True)
    bio = models.CharField(max_length=100, default='',null=True)
    profile_picture = models.ImageField(upload_to='profile_pic',default='emptyprofilepic.jpg')
    bio = models.CharField(max_length=500, default='',null=True)
    d_o_b = models.DateTimeField('Date of birth', null=True)

    def __str__(self):
        return f'{self.user.username} Profile'



class UserFollowing(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="followers")
    following_user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")

    class Meta:
        unique_together=[['user_id','following_user_id']]

    def __str__(self):
        return (f"{self.user_id} is followed by {self.following_user_id}")





class InstaPost(models.Model):
    user = models.ForeignKey(Profile,on_delete=models.DO_NOTHING, null=True)
    picture = models.ImageField(upload_to="posts",null=True)
    post_title = models.CharField(max_length=200,null=True)
    caption = models.CharField(max_length=500,null=True)
    pub_date = models.DateTimeField('Date Published',null=True)

    def __str__(self):
        return self.post_title

    def was_published_recently(self):
        now=timezone.now()
        return now - datetime.timedelta(days=3) <= self.pub_date <= now

class Like(models.Model):
    post = models.ForeignKey(InstaPost, on_delete=models.CASCADE)
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)

class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(InstaPost, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.comment_text

class CommentLike(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)



    #cd /d C:/Users/sam/PycharmProjects/InstaClone

register/models.py
from django.db import models

# Create your models here.

instaclone/forms.py
from django import forms
from .models import Profile, InstaPost, UserFollowing

class ImageFormProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields=('profile_picture',)

class ImageForm(forms.ModelForm):
    class Meta:
        model = InstaPost
        fields =('picture','post_title','caption',)

class FollowForm(forms.ModelForm):
    class Meta:
        model = UserFollowing
        fields = ('user_id','following_user_id',)

register/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

YEARS = [x for x in range(1900,2030)]

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    d_o_b = forms.DateTimeField(label='Date of birth',
                                widget=forms.SelectDateWidget(years=YEARS))

    class Meta:
        model = User
        fields = ["username","email","password1","password2", "d_o_b",]

instaclone/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ImageForm, ImageFormProfile, FollowForm
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.urls import reverse
from instaclone.models import InstaPost, UserFollowing, Profile
from django.contrib.auth.models import User
from django.views.generic.detail import DetailView
# Create your views here.

def index(response):
    return HttpResponse("hello")

def home(response):
    return render(response, "instaclone/home.html")


@login_required
def my_profile(request):
    template = loader.get_template('instaclone/my_profile.html')
    return HttpResponse(template.render({}, request))

def change_profile_pic(request):
    if request.method == 'POST':
        form = ImageFormProfile(request.POST,request.FILES)
        if form.is_valid():
            user=request.user
            user.profile.profile_picture = request.FILES.get('profile_picture',user.profile.profile_picture)
            user.profile.save()
            form.save()

            return HttpResponseRedirect(reverse('instaclone:my_profile'))
    else:
        form=ImageFormProfile()
    return render(request, "instaclone/profile_pic.html", {"form":form})



def upload(request):
    if request.method == 'POST':
        form = ImageForm(request.POST,request.FILES)
        if form.is_valid():
            user=request.user
            p=InstaPost(
                user = user.profile,
                picture = request.FILES.get('picture'),
                post_title = form.cleaned_data.get('post_title'),
                caption = form.cleaned_data.get('caption'),
                pub_date = timezone.now()

            )

            p.save()
            form.save()
            return HttpResponseRedirect(reverse('instaclone:my_profile'))
    else:
        form=ImageForm()
    return render(request, "instaclone/upload.html", {"form":form})




def followers(request, username):
    user = User.objects.get(username=username)
    template = loader.get_template('instaclone/followers.html')
    return HttpResponse(template.render({'user':user}, request))

def following(request, username):
    user = User.objects.get(username=username)
    template = loader.get_template('instaclone/following.html')
    return HttpResponse(template.render({'user':user}, request))

def profileview(request, username):
    user_profile = User.objects.get(username=username)
    template = loader.get_template('instaclone/profile.html')
    return HttpResponse(template.render({'user_profile':user_profile}, request))

def follow(request, username):
    user = User.objects.get(username=username)
    template = loader.get_template('instaclone/follow.html')
    return HttpResponse(template.render({'user':user}, request))

register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from instaclone.models import Profile



# Create your views here.

def register(request):
    if request.method =="POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user=form.save()
            profile=Profile.objects.create(
                user = user,
                username = form.cleaned_data['username'],
                d_o_b = form.cleaned_data['d_o_b']
            )

            profile.save()
            return redirect('/home')
    else:
        form = RegisterForm()
    return render(request, 'register/register.html', {'form': form,})

instaclone/templates/instaclone/base.html
<!DOCTYPE html>

<html>
<head>
    <title{% block title %}Sam's Website{% endblock %}</title>
</head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<style type="text/css">

    .navbar ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #69A7F1;
        width: 100%;
        white-space: nowrap;
    }
    .navbar li {
        float: left;
        font-size: 20px;

       }
    .navbar li a {
    display: block;
    text-decoration: none;
    colour:#EEFEF6;
    text-align: center;
    padding: 14px 16px;
    color: white;

    }
    li a:hover:not(.active) {
    background-color: #002F8D ;
    }

    .home {
      background-color: #1D65F5;
    }



</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous">

<body>
    <div class="navbar">
        <ul>
            <li><a class="home" href="/home">Home</a></li>
            <li><a href="/login">Login</a></li>
            <li><a href="/register">Register</a></li>
            <li><a href="/my_profile">Profile</a></li>
        </ul>
    </div>

    <div id="content" name="content" class="main">
        <div class="row justify-content-center">
            <div class="col-8">
                <hi class="mt-2">InstaClone</hi>
                <hr class="mt-0 mb-8">

        {% block content %}
        {% endblock %}
            </div>
        </div>
    </div>
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>


</html>

instaclone/templates/instaclone/follow.html
{% extends "instaclone/base.html" %}
{% block title %}My Profile{% endblock %}

{% block content %}
{% if user.is_authenticated %}
{% if UserFollowing.objects.filter(user_id=other_user, following_user_id=request.user).exists=True %}
{% endif %}
{% endif %}
{% endblock %}

instaclone/templates/instaclone/followers.html
{% extends "instaclone/base.html" %}
{% block title %}Followers{% endblock %}

{% block content %}
{% for followers in user.followers.all %}
<p>{{ followers.following_user_id }}</p>
{% endfor %}



{% endblock %}

instaclone/templates/instaclone/following.html
{% extends "instaclone/base.html" %}
{% block title %}Following{% endblock %}

{% block content %}
{% for following in user.following.all %}
<p>{{ following.user_id }}</p>
{% endfor %}



{% endblock %}

instaclone/templates/instaclone/home.html
{% extends "instaclone/base.html" %}
{% block title %}S{% endblock %}

{% block content %}
    Home
{% endblock %}

instaclone/templates/instaclone/my_profile.html
{% extends "instaclone/base.html" %}
{% block title %}My Profile{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <h1>{{ user.username }}'s Profile</h1>
    <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture" width="150" height="120" class="rounded-circle">

    <ul>
        <li><a href="/profile_pic/">Upload Profile Pic</a></li>
        <li><a href="/upload">Upload Photo</a></li>
        <li><a href="http://127.0.0.1:8000/followers/{{ user.username }}/">Followers</a></li>
        <li><a href="http://127.0.0.1:8000/following/{{ user.username }}/">Following</a></li>

    </ul>1

    {% for photo in user.profile.instapost_set.all %}
    <img src="{{ photo.picture.url }}" width="150" height="120">
    {% endfor %}
{% endif %}

{% endblock %}

instaclone/templates/instaclone/profile.html
{% extends "instaclone/base.html" %}#
{% block title %}Profile{% endblock %}

{% block content %}

 <h1>{{ user_profile.username }}'s Profile</h1>
<img src="{{ user_profile.profile.profile_picture.url }}" alt="Profile Picture" width="150" height="120" class="rounded-circle">
<ul>

    <li><a href="http://127.0.0.1:8000/followers/{{ user_profile.username }}/">Followers</a></li>
    <li><a href="http://127.0.0.1:8000/following/{{ user_profile.username }}/">Following</a></li>
</ul>

{% for photo in user_profile.profile.instapost_set.all %}
    <img src="{{ photo.picture.url }}" width="150" height="120">
    {% endfor %}
{% endblock %}

instaclone/templates/instaclone/profile_pic.html
{% extends "instaclone/base.html" %}
{% block title %}Upload Profile Picture{% endblock %}

{% block content %}
    <h1>{{ user.username }}'s Profile</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit", name="save_pp">Upload Prof_Pic</button>
    </form>
{% endblock %}

instaclone/templates/instaclone/upload.html
{% extends "instaclone/base.html" %}
{% block title %}Upload Picture{% endblock %}

{% block content %}
    <h1>Upload Photo</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit"  name="upload">Upload Picture</button>
    </form>
{% endblock %}

register/templates/register/register.html
{% extends "instaclone/base.html" %}

{% block title %}Create an Account{% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" name="Register">Register</button>
    </form>
{% endblock %}